### ISSUE TITLE
Multi-property explicit tests not recognized

### ISSUE THREAD

**Issue by shivjm** [Modernizr/customizr#19]
If a Modernizr test populates multiple properties (e.g. [hyphens.js](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/css/hyphens.js)), customizr ignores those properties in the explicit tests list, because [it matches the test name against the array](https://github.com/doctyper/customizr/blob/develop/src/crawler.js#L171).  Quick fix (assuming the hierarchy doesn’t go more than two levels deep):

``` javascript
                    return (data.property === test) || (data.property.indexOf(test) > -1);
```

**Comment by backflip** [comment]
I just ran into this issue with `progressbar`. @doctyper, would you consider a pull request with this change?

**Comment by rejas** [comment]
Hi @shivjm this should be fixed in v1 thanks to https://github.com/Modernizr/customizr/pull/44/
