### ISSUE TITLE
Looking for Modernizr references

### ISSUE THREAD

**Issue by orest22** [Modernizr/customizr#32]
I'm trying to use new grunt-modernizr with this config:
```
modernizr: {

            dist: {
                "parseFiles": true,
                "customTests": [],
                "devFile": 'node_modules/grunt-modernizr/build/modernizr-custom.js',
                "dest" : false,
                "outputFile": "js/modernizr.min.js",
                "tests": ['touchevents'],
                "extensibility": [
                    "setClasses"
                ],
                "uglify": true
            }


        }
```

version of grunt-modernizr is latest. 

And I'm getting this message "Looking for Modernizr references" and it breaks on that and doesn't generate any file am I doing something wrong? Could some body help me with that?

**Comment by breams** [comment]
Adding `"crawl": false` should fix the issue for you.

**Comment by patrickkettner** [comment]
Thanks @breams!

**Comment by skynet** [comment]
Thanks for asking and thanks for responding. Took me 30 min to figure out why this Grunt task was silently failing.
