### ISSUE TITLE
Unable to include tests wich are specified as an array

### ISSUE THREAD

**Issue by Schleuse** [Modernizr/customizr#43]
It is currently not possible to include Tests like CSS-hyphens because it has to be specified as an array, which customizr doesn't properly handle.

Example (Generated with the Modernizr Download Builder):
```json
{
  "crawl": false,
  "customTests": [],
  "dest": "/PATH/TO/modernizr-output.js",
  "tests": [
    "flexbox",
    [
      "csshyphens",
      "softhyphens",
      "softhyphensfind"
    ]
  ],
  "options": [
    "setClasses"
  ],
  "uglify": true
}
```

**Comment by rejas** [comment]
hi @Schleuse you can close this now, v1 is release with your fix for it :-)

**Comment by Schleuse** [comment]
Niiiice 😀
