### ISSUE TITLE
References to HTML5 features such as display flex and details/summary not found

### ISSUE THREAD

**Issue by smohadjer** [Modernizr/customizr#46]
I'm using the gulp-modernizr plugin and when crawling my css, it fails to pickup references to display: flex, or use of "summary" and "details" selectors and hence no classes are added to HTML element for those. Any idea what's wrong?

**Comment by rejas** [comment]
hi @smohadjer the crawl option, when going through css files, will not look for `display: flex` but rather if you are using a css selector that are named like the Modernizr properties, like this 
```
.flexbox {
  ...
}
```
or
```
.no-flexbox {
  ...
}
```
Hope that clears your problem, I will try to make it clearer in the docs too.

**Comment by smohadjer** [comment]
But why? Such selectors are totally arbitrary and have nothing to do with the flexbox spec. On the other hand if crawler searches for "display: flex;" it won't miss any cases where flexbox is being used.

**Comment by smohadjer** [comment]
What about details/summary?

**Comment by rejas** [comment]
The selectors are not arbitrary but the only way for the crawler to know what to look for. Becuase if he finds one of them he can be pretty sure that you want to test against for example "flexbox" by using something like 
```
.foo {
  display: flex;
}
.no-flexbox {
  .foo {
    display: block;
  }
}
```

If the crawler would just be looking for `display: flex` he couldnt know if you really wanted to have that test or if you are using modern browsers and dont care about Modernizrs tests. 

But if you were actually adding a codepath behind the test (be it css or js) he'd see your code utilizing the test and generate a build with it.
