### ISSUE TITLE
Transfer ownership to Modernizr team

### ISSUE THREAD

**Issue by rejas** [Modernizr/customizr#67]
Not sure if https://github.com/Modernizr/customizr/issues/28 got reverted or if just I dont have enough rights here, but could you @doctyper or @patrickkettner look into why this repo is not part of the Modernizr repos?

**Comment by doctyper** [comment]
Not sure I understand. This repo is under the Modernizr organization.

**Comment by rejas** [comment]
Sorry, to be clearer: yes, its part of Modernizr but only in one of the teams:
https://github.com/orgs/Modernizr/teams/team-modernizr/repositories

There are two other teams which dont seem to have access to it. Do you know why there are three at all and if you could add it to the larger Owner team too?

**Comment by rejas** [comment]
hi @doctyper any chance to add the other teams to the customizr project too?

**Comment by rejas** [comment]
hi @doctyper sorry to bother you again. But ould you take a look if you can change something in the settings of this repo? I cant see the settings tab myself although I am part of the Modernizr team.

**Comment by doctyper** [comment]
@rejas Done. GitHub mucked with owner settings and that seems to have dropped admin roles for this repo.

**Comment by rejas** [comment]
Thanks :-) I jsut disabled the wiki to test it out :-)
