### ISSUE TITLE
Customizr dependency optimist is deprecated and should be replaced with yargs to remedy prototype pollution

### ISSUE THREAD

**Issue by rediris** [Modernizr/customizr#72]
```
=== npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution
  Package         minimist
  Patched in      >=0.2.1 <1.0.0 || >=1.2.3
  Dependency of   gulp-modernizr [dev]
  Path            gulp-modernizr > customizr > optimist > minimist
  More info       https://npmjs.com/advisories/1179
  ```
  
  
 See: https://www.npmjs.com/advisories/1179

Also see the deprecation notice at the top of: https://www.npmjs.com/package/optimist

**Comment by rejas** [comment]
Thx for the heads up, will move it into the customizr repo. Might you be interested in providing a PR for this?

**Comment by rediris** [comment]
> Thx for the heads up. Might you be interested in providing a PR for this?

Just submitted a PR, but it's failing the tests, not quite sure why.

**Comment by rejas** [comment]
You seem to have branched of from an old master, which will fail since Modenrizr has gotten new tests in the meantime (which customizr tests wont recognize). If you rebase it to the latest master (or merge master into your branch) it should run fine.

**Comment by rejas** [comment]
Fixed it myself, thanks for the PR and issue.
