### ISSUE TITLE
https://github.com/Modernizr/customizr/tarball/develop: Request failed "404 Not Found"

### ISSUE THREAD

**Issue by zsyborg** [Modernizr/customizr#78]
Error oocured while npm install for https://github.com/Frainlar/Frainlar-ERP repo

Error Log

Trace: 
  Error: https://github.com/Modernizr/customizr/tarball/develop: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (C:\Users\zasha\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:696:66)
      at new ResponseError (C:\Users\zasha\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:802:124)
      at Request.<anonymous> (C:\Users\zasha\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:66215:16)
      at Request.emit (node:events:511:28)
      at module.exports.Request.onRequestResponse (C:\Users\zasha\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:141767:10)
      at ClientRequest.emit (node:events:511:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at TLSSocket.socketOnData (node:_http_client:535:22)
      at TLSSocket.emit (node:events:511:28)

package.json

{
  "name": "easyErp",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "test": "mocha test/serverSpecs/**/*.js",
    "postinstall": "bower install"
  },
  "dependencies": {
    "amqp": "^0.2.7",
    "async": "~1.5.0",
    "body-parser": "^1.10.2",
    "bower": "^1.7.9",
    "compression": "^1.6.2",
    "connect-mongo": "^0.8.0",
    "connect-multiparty": "^1.2.5",
    "consolidate": "^0.12.1",
    "cookie-parser": "^1.3.3",
    "crypto": "0.0.3",
    "debug": "^2.2.0",
    "express": "^4.5.0",
    "express-session": "^1.13.0",
    "express-subdomain": "1.0.3",
    "fast-csv": "^0.6.0",
    "geoip-lite": "^1.1.6",
    "getresponse-nodejs-api": "0.0.4",
    "googleapis": "39.1.0",
    "html-pdf": "^2.1.0",
    "isodate": "^0.1.4",
    "js-zimbra": "^1.0.0-beta.6",
    "lodash": "4.17.21",
    "moment": "^2.24.0",
    "money": "^0.2.0",
    "mongodb": "3.1.13",
    "mongoose": "^5.7.5",
    "mongoose-schema-extend": "^0.2.0",
    "morgan": "^1.9.1",
    "mssql": "2.1.3",
    "newrelic": "1.18.3",
    "node-schedule": "^0.2.9",
    "node-xlsx": "^0.6.0",
    "nodemailer": "^6.4.16",
    "oauth": "^0.9.15",
    "open-exchange-rates": "^0.3.0",
    "pmx": "^0.3.31",
    "redis": "^1.0.0",
    "request": "^2.88.2",
    "socket.io": "^2.4.0",
    "socket.io-redis": "^0.1.4",
    "swig": "1.4.2",
    "underscore": "^1.12.1",
    "validate.js": "^0.9.0",
    "validator": "^4.2.1",
    "winston": "^2.1.1",
    "woocommerce-api": "^1.3.2",
    "xlsx": "^0.17.0",
    "xml2js": "0.4.0",
    "xss-filters": "^1.2.7"
  },
  "apidoc": {
    "title": "Custom apiDoc browser title",
    "url": "http://192.168.88.122"
  },
  "devDependencies": {
    "apidoc": "^0.16.1",
    "autoprefixer": "^6.3.7",
    "chai": "^3.2.0",
    "chai-jquery": "^2.0.0",
    "coveralls": "^2.11.6",
    "eslint": "^4.18.2",
    "eslint-config-thinkmobiles": "git+https://github.com/ivanlyah/eslint-config-thinkmobiles.git",
    "eslint-plugin-react": "^4.1.0",
    "grunt": "^1.3.0",
    "grunt-apidoc": "^0.11.0",
    "grunt-contrib-jshint": "^0.11.2",
    "grunt-contrib-nodeunit": "^0.4.1",
    "grunt-contrib-sass": "^1.0.0",
    "grunt-contrib-uglify": "^0.9.1",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-jsdoc": "^0.6.8",
    "grunt-karma": "^0.12.1",
    "grunt-modernizr": "^1.0.1",
    "grunt-postcss": "^0.8.0",
    "istanbul": "^0.4.2",
    "jasmine-core": "^2.4.1",
    "jsdoc": "^3.3.2",
    "karma": "^1.3.0",
    "karma-chai": "^0.1.0",
    "karma-chai-jquery": "^1.0.0",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coverage": "^0.5.3",
    "karma-firefox-launcher": "^0.1.7",
    "karma-fixture": "^0.2.5",
    "karma-html2js-preprocessor": "^0.1.0",
    "karma-ie-launcher": "^0.2.0",
    "karma-jquery": "^0.1.0",
    "karma-mocha": "^0.2.1",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-requirejs": "^0.2.3",
    "karma-safari-launcher": "^0.1.1",
    "karma-sinon": "^1.0.4",
    "karma-sinon-chai": "^1.1.0",
    "mocha": "^2.3.4",
    "mocha-lcov-reporter": "^1.0.0",
    "open": "6.0.0",
    "phantomjs-prebuilt": "2.1.4",
    "pixrem": "^3.0.1",
    "requirejs": "2.1.22",
    "sinon": "1.17.2",
    "sinon-chai": "2.8.0",
    "supertest": "1.0.1"
  }
}

**Comment by patrickkettner** [comment]
It looks like that Frainlar-ERP was explicitly installing customizr from the develop branch, and that got baked into their package-lock.json. That branch got deleted. You can update the package-lock.json file in Frainlar-ERP to point to `/main` instead of `/develop` for cutstomizr. You will also need to update the sha512 value to `sha512-XmDKvxaYWEPeF4Mib5I5iD0zwAM3KHOqxFferqgx7wGu//YaA566YJkP56ixWBg/RIQd2FBQxxOOa+FNFcdnCw==`. 

Normally you would just delete the package-lock.json file and reinstall, but I dont know how many other oddities are in there, so this is the path of least modification
